"""add route station

Revision ID: a5a0fd520afc
Revises: 4f59325b7f83
Create Date: 2026-07-31 18:51:05.249203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a0fd520afc'
down_revision: Union[str, Sequence[str], None] = '4f59325b7f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('halt_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_from_source', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_route_sequence'),
    sa.UniqueConstraint('route_id', 'station_id', name='uq_route_station')
    )
    op.create_index('ix_route_station_route_sequence', 'route_stations', ['route_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_route_stations_id'), 'route_stations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stations_id'), table_name='route_stations')
    op.drop_index('ix_route_station_route_sequence', table_name='route_stations')
    op.drop_table('route_stations')
    # ### end Alembic commands ###
