"""recreate train table

Revision ID: b94afaee3abf
Revises: YOUR_NEW_REVISION_ID
Create Date: 2026-08-05 17:57:49.667563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94afaee3abf'
down_revision: Union[str, Sequence[str], None] = 'YOUR_NEW_REVISION_ID'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=10), nullable=False),
    sa.Column('train_name', sa.String(length=150), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('return_train_number', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_train_name'), 'trains', ['train_name'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_foreign_key(None, 'schedules', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_train_name'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    # ### end Alembic commands ###
