"""add unique constraint on schedules train_id route_id

Revision ID: 0bb6977d93aa
Revises: c1686aac749b
Create Date: 2026-08-19 10:56:01.396637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb6977d93aa'
down_revision: Union[str, Sequence[str], None] = 'c1686aac749b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_schedule_train_route', 'schedules', ['train_id', 'route_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_schedule_train_route', 'schedules', type_='unique')
    # ### end Alembic commands ###
